### ISSUE TITLE
Error on start when using environment variables

### ISSUE THREAD

**Issue by erbridge** [stormpath/stormpath-express#99]
As described in the docs, I'm setting the following environment variables:

```
STORMPATH_CLIENT_APIKEY_ID=YOUR-ID-HERE
STORMPATH_CLIENT_APIKEY_SECRET=YOUR-SECRET-HERE
STORMPATH_APPLICATION_HREF=YOUR-APP-HREF
```

When starting, The following exception occurs:  `No client config found. This is a required configuration option.` Looking at the code, I can't see where those options are parsed, so are they a removed feature?

Running off 80315b2655500008c966d5d2c1cc679ca58a892b (while waiting for the fix for #87 to be released).

**Comment by baer** [comment]
Can you post your config too? It's not that well documented yet so it could just be an error in your code.

**Comment by erbridge** [comment]
Config:

```js
{
  // client: {
  //   apiKey: {
  //     id: process.env.STORMPATH_CLIENT_APIKEY_ID,
  //     secret: process.env.STORMPATH_CLIENT_APIKEY_SECRET,
  //   },
  // },
  // application: {
  //   href: process.env.STORMPATH_APPLICATION_HREF,
  // },

  expand: {
    customData: true,
  },

  website: true,
  web: {
    register: {
      enabled:       true,
      autoLogin:     true,
      autoAuthorize: true,
      fieldOrder: [
        'username',
        'email',
        'givenName',
        'surname',
        'password',
        'passwordConfirm',
      ],
    },
    login: {
      enabled: true,
    },
    logout: {
      enabled: true,
    },
    forgotPassword: {
      enabled: true,
    },
    changePassword: {
      enabled:   true,
      autoLogin: true,
    },
  },

  postRegistrationHandler: function(account, req, res, next) {
    // Do stuff.

    next();
  },
}
```

Note this isn't an issue on `2.0.4`

**Comment by erbridge** [comment]
And the full stacktrace in case that helps:

```
Error: No client config found. This is a required configuration option.
    at Config.validate (/path/to/project/node_modules/express-stormpath-config/lib/config.js:31:14)
    at initClient (/path/to/project/node_modules/express-stormpath/lib/stormpath.js:36:10)
    at Object.module.exports.init (/path/to/project/node_modules/express-stormpath/lib/stormpath.js:78:16)
    at Object.<anonymous> (/path/to/project/app.js:102:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by robertjd** [comment]
I just merged a change that should fix this, released at 2.0.5

Can you git it a try?  Thanks :)

**Comment by erbridge** [comment]
Yup, that fixed it, thanks.

**Comment by agonbina** [comment]
In the docs it says that along the other env variables we need to also set ```STORMPATH_CLIENT_APPLICATION_HREF``` but the SDK won't read it. Instead its looking for ```STORMPATH_APPLICATION_HREF```. Just thought you should update the docs here: http://docs.stormpath.com/nodejs/express/latest/configuration.html to reflect this
